# Site settings
title: Apiwise - Small, Big, Linked, Open en/of Closed data op een 'developer-friendly' wijze
baseurl: ""
url: "http://www.apiwise.nl"
twitter_username: apiwise

# Build settings
markdown: kramdown
