# Site settings
title: Apiwise - Small, Big, Linked, Closed en/of Open Data met behulp van state-of-the-art semantische web API's
baseurl: ""
url: "http://www.apiwise.nl"
twitter_username: apiwise

# Build settings
markdown: kramdown
